export default {
  home: '/',
  onboarding: '/onboarding',
  onboardingAccount: '/onboarding/account',
  onboardingHelp: '/onboarding/help',
  onboardingPayment: '/onboarding/payment',
  onboardingVisit: '/onboarding/visit',
  paymentMethod: '/payment-method',
  profile: '/profile',
  privacyAndTerms: '/privacy-and-terms',
  serviceHistory: '/service-history',
  services: '/services',
  settings: '/settings',
  support: '/support',
  upcomingServices: '/upcoming-services',
  visitNew: '/visits/new',
  visit: '/visits/:id',
  visitRelease: '/visits/:id/release',
  hubspotOnboarding: 'https://meetings.hubspot.com/info4832/onboarding-meeting',
  helpersFAQ: 'http://www.gethelpers.ca/faq.html',
};
